name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag sprx7767/azdtest:latest 
    - uses: docker/login-action@v1.12.0
    - name: Docker Login
      with:
          username:  ${{ secrets.DOCKER_USERNAME }}
          password:  ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker push
      run: docker push sprx7767/azdtest:latest
