name: Docker Hub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Code
    - uses: mr-smithers-excellent/docker-build-push@v5
      with:
         image: sprx7767/azdtest
         registry: docker.io
         addLatest: True
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
